import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ticket Web App",
  description: "Generated by Hrittik Chatterjee",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <Nav></Nav>
          <div className="flex-grow overflow-y-auto  bg-slate-800  text-gray-300">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
